[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "deck_clustering"
version = "0.0.1"
description = ""
dependencies = [
    "numpy ==2.2.4",
    "pandas ==2.2.3",
    "matplotlib ==3.10.1",
    "torch ==2.6.0",
    "pytorch-lightning ==2.5.1",
]
